name: XU Plugin Template
version: 1
description: Demo
author: XU
website: xu-university.de

main: com.xu.example.DeinPlugin.DeinPlugin

commands:
    beispiel:
        description: Ein Beispiel-Befehl
        permission: deinplugin.beispiel
        usage: /<command>

permissions: {}
